# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
airline_1 = Airline.create(name: "American Airlines")
airline_2 = Airline.create(name: "Southwest Airlines")
airline_3 = Airline.create(name: "Delta Airlines")

flight_1 = Flight.create(number: "AA1234", airline_id: airline_1.id, date: "01/01/2020", departure_city: "Denver", arrival_city: "Reno")
flight_2 = Flight.create(number: "UA1234", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_3 = Flight.create(number: "DL1234", airline_id: airline_3.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_4 = Flight.create(number: "UA1235", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_5 = Flight.create(number: "UA1236", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_6 = Flight.create(number: "UA1237", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_7 = Flight.create(number: "UA1238", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_8 = Flight.create(number: "UA1239", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_9 = Flight.create(number: "UA1240", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")
flight_10 = Flight.create(number: "UA1241", airline_id: airline_2.id, date: "01/01/2020", departure_city: "New York", arrival_city: "Orlando")

passenger_1 = Passenger.create(name: "John Doe", age: 11)
passenger_2 = Passenger.create(name: "Allen Allenson", age: 22)
passenger_3 = Passenger.create(name: "Billy Billyson", age: 33)
passenger_4 = Passenger.create(name: "Cathy Catyson", age: 44)
passenger_5 = Passenger.create(name: "David Dyson", age: 55)
passenger_6 = Passenger.create(name: "Earl Earlson", age: 66)
passenger_7 = Passenger.create(name: "Frank Frankson", age: 77)
passenger_8 = Passenger.create(name: "George Georgeson", age: 88)

flights_passenger_1 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_1.id)
flights_passenger_2 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_2.id)
flights_passenger_3 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_3.id)
flights_passenger_4 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_4.id)
flights_passenger_5 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_5.id)
flights_passenger_6 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_6.id)
flights_passenger_7 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_7.id)
flights_passenger_8 = FlightsPassenger.create(flight_id: flight_1.id, passenger_id: passenger_8.id)
flights_passenger_9 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_1.id)
flights_passenger_10 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_2.id)
flights_passenger_11 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_3.id)
flights_passenger_12 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_4.id)
flights_passenger_13 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_5.id)
flights_passenger_14 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_6.id)
flights_passenger_15 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_7.id)
flights_passenger_16 = FlightsPassenger.create(flight_id: flight_2.id, passenger_id: passenger_8.id)
flights_passenger_17 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_1.id)
flights_passenger_18 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_2.id)
flights_passenger_19 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_3.id)
flights_passenger_20 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_4.id)
flights_passenger_21 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_5.id)
flights_passenger_22 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_6.id)
flights_passenger_23 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_7.id)
flights_passenger_24 = FlightsPassenger.create(flight_id: flight_3.id, passenger_id: passenger_8.id)
flights_passenger_25 = FlightsPassenger.create(flight_id: flight_4.id, passenger_id: passenger_1.id)